<h1 style='text-align:center'><b>MODEL TRAINING</b></h1>

**IMPORT LIBRARIES**

In [91]:
import pandas as pd
import numpy as np

**IMPORT DATASET**

In [92]:
df = pd.read_csv("D:\Downloads\instagram_reach.csv")

In [93]:
df.head()

Unnamed: 0  S.No              USERNAME  \
0           0     1         mikequindazzi   
1           1     2       drgorillapaints   
2           2     3    aitrading_official   
3           3     4  opensourcedworkplace   
4           4     5           crea.vision   

                                             Caption  Followers  \
0  Who are #DataScientist and what do they do? >>...       1600   
1  We all know where it’s going. We just have to ...        880   
2  Alexander Barinov: 4 years as CFO in multinati...        255   
3                                               sfad        340   
4  Ever missed a call while your phone was chargi...        304   

                                            Hashtags Time since posted  Likes  
0  #MachineLearning #AI #DataAnalytics #DataScien...          11 hours    139  
1   #deck .#mac #macintosh#sayhello #apple #steve...           2 hours     23  
2  #whoiswho #aitrading #ai #aitradingteam#instat...           2 hours     25  
3  #iot #cre#workplace #CDO #bigdata #technology#...           3 hours     49  
4  #instamachinelearning #instabigdata#instamarke...           3 hours     30

In [94]:
df.tail()

Unnamed: 0  S.No        USERNAME  \
95           8    19  michaelgarza__   
96           9    21     dvlp_search   
97          10    22      ecom.space   
98          11    24  lb3enterprises   
99          12    25    palmariusdev   

                                              Caption  Followers  \
95  328 S. Wetherly Drive, Beverly Hills, CA 90212...        614   
96  Credit @tristankappel To find more dvlp follow...        450   
97  We are coming up with the Best 21 Books that w...        182   
98  We’re only paid to move dirt once. It’s not ju...       2039   
99                    Obtén tu tienda en línea ahora.        741   

                                             Hashtags Time since posted  Likes  
95  #beverlyhills #realestate#losangelesrealestate...           3 hours     31  
96  #workspace #work #developer#development #devel...           3 hours     42  
97  #books #book #motivation #inspiration #life#bo...           3 hours     10  
98  #heavyequipment #underconstruction#dozer #real...           3 hours    222  
99  #marketing #programming#development #desarroll...           3 hours    109

In [95]:
df.sample(5)

Unnamed: 0  S.No       USERNAME  \
41           2    10      ricmiqads   
58          19    27        ivarski   
8            8     9    ethicsandai   
92           5    15  caseyjmcclure   
39           0     5  mikequindazzi   

                                              Caption  Followers  \
41  One rare and remarkable approach in the overhe...        105   
58             Morning swim before the sun is up 🇮🇹☀️        918   
8   Having a great week at @ldntechweek exploring ...         13   
92  Picked up this roubo bookstand from my buddy o...        106   
39  1 in 3 #Smartphones will ship w/ #MachineLearn...       1600   

                                             Hashtags Time since posted  Likes  
41                        #ai #artificialintelligence           2 hours      8  
58   #livinginitaly #tuscanyitaly#summerinitaly🇮🇹 ...           2 hours     21  
8   #LTW #London #TechXLR8 #Technology#AI #Artific...           4 hours     22  
92  #cybersecurity #programmer #development#nerd #...           2 hours     12  
39   #MachineLearning #artificialintelligence#AI #IoT          14 hours    136

In [96]:
df.shape

(100, 8)

In [97]:
df.columns

Index(['Unnamed: 0', 'S.No', 'USERNAME', 'Caption', 'Followers', 'Hashtags',
       'Time since posted', 'Likes'],
      dtype='object')

**DROP UNWANTED COLUMN FROM DATASET**

In [98]:
df.drop(['Unnamed: 0', 'S.No'], axis = 1, inplace = True)

In [99]:
df.shape

(100, 6)

**Change the Datatypes of Time since posted**

In [100]:
Time_since_posted_hours = []

for i in df['Time since posted']:
    Time_since_posted_hours.append(i.replace('hours','')) 

se = pd.Series(Time_since_posted_hours)
df['Time since posted (hours)'] = se.values
df['Time since posted (hours)'] = pd.to_numeric(df['Time since posted (hours)'])
df = df.drop('Time since posted', axis = 1)

In [101]:
df

USERNAME                                            Caption  \
0          mikequindazzi  Who are #DataScientist and what do they do? >>...   
1        drgorillapaints  We all know where it’s going. We just have to ...   
2     aitrading_official  Alexander Barinov: 4 years as CFO in multinati...   
3   opensourcedworkplace                                               sfad   
4            crea.vision  Ever missed a call while your phone was chargi...   
..                   ...                                                ...   
95        michaelgarza__  328 S. Wetherly Drive, Beverly Hills, CA 90212...   
96           dvlp_search  Credit @tristankappel To find more dvlp follow...   
97            ecom.space  We are coming up with the Best 21 Books that w...   
98        lb3enterprises  We’re only paid to move dirt once. It’s not ju...   
99          palmariusdev                    Obtén tu tienda en línea ahora.   

    Followers                                           Hashtags  Likes  \
0        1600  #MachineLearning #AI #DataAnalytics #DataScien...    139   
1         880   #deck .#mac #macintosh#sayhello #apple #steve...     23   
2         255  #whoiswho #aitrading #ai #aitradingteam#instat...     25   
3         340  #iot #cre#workplace #CDO #bigdata #technology#...     49   
4         304  #instamachinelearning #instabigdata#instamarke...     30   
..        ...                                                ...    ...   
95        614  #beverlyhills #realestate#losangelesrealestate...     31   
96        450  #workspace #work #developer#development #devel...     42   
97        182  #books #book #motivation #inspiration #life#bo...     10   
98       2039  #heavyequipment #underconstruction#dozer #real...    222   
99        741  #marketing #programming#development #desarroll...    109   

    Time since posted (hours)  
0                          11  
1                           2  
2                           2  
3                           3  
4                           3  
..                        ...  
95                          3  
96                          3  
97                          3  
98                          3  
99                          3  

[100 rows x 6 columns]

In [102]:
df.to_csv("D:\instagram\data\inst1.csv")

In [103]:
df.columns

Index(['USERNAME', 'Caption', 'Followers', 'Hashtags', 'Likes',
       'Time since posted (hours)'],
      dtype='object')

**Seperate Independent & Dependent Features of Dataset**

In [104]:
X = df.drop(['Caption', 'Likes','Time since posted (hours)'], axis = 1)
y = df['Time since posted (hours)']

In [105]:
X

USERNAME  Followers  \
0          mikequindazzi       1600   
1        drgorillapaints        880   
2     aitrading_official        255   
3   opensourcedworkplace        340   
4            crea.vision        304   
..                   ...        ...   
95        michaelgarza__        614   
96           dvlp_search        450   
97            ecom.space        182   
98        lb3enterprises       2039   
99          palmariusdev        741   

                                             Hashtags  
0   #MachineLearning #AI #DataAnalytics #DataScien...  
1    #deck .#mac #macintosh#sayhello #apple #steve...  
2   #whoiswho #aitrading #ai #aitradingteam#instat...  
3   #iot #cre#workplace #CDO #bigdata #technology#...  
4   #instamachinelearning #instabigdata#instamarke...  
..                                                ...  
95  #beverlyhills #realestate#losangelesrealestate...  
96  #workspace #work #developer#development #devel...  
97  #books #book #motivation #inspiration #life#bo...  
98  #heavyequipment #underconstruction#dozer #real...  
99  #marketing #programming#development #desarroll...  

[100 rows x 3 columns]

In [106]:
y

0     11
1      2
2      2
3      3
4      3
      ..
95     3
96     3
97     3
98     3
99     3
Name: Time since posted (hours), Length: 100, dtype: int64

**DEFINE CATEGORICAL & NUMERICAL FEATURES**

In [107]:
cat_columns = X.columns[X.dtypes == 'object']
cat_columns

Index(['USERNAME', 'Hashtags'], dtype='object')

In [108]:
num_columns = X.columns[X.dtypes != 'object']
num_columns

Index(['Followers'], dtype='object')

In [109]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OrdinalEncoder

**PIPELINES**

In [110]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

**Categorical Pipeline**

In [111]:
cat_pipeline = Pipeline(
    steps = [
        ('imputer', SimpleImputer(strategy = 'most_frequent')),
        ('ordinalencoder', OrdinalEncoder(handle_unknown = 'use_encoded_value', unknown_value = -1)),
    ]
)

In [112]:
cat_pipeline

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('ordinalencoder',
                 OrdinalEncoder(handle_unknown='use_encoded_value',
                                unknown_value=-1))])

**Numerical Pipeline**

In [113]:
num_pipeline = Pipeline(
    steps = [
        ('imputer', SimpleImputer(strategy = 'median')),
        ('scaler', StandardScaler()),
    ]
)

In [114]:
num_pipeline

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler())])

**COMBINE TWO PIPELINES**

In [115]:
preprocessor = ColumnTransformer(
    [
        ('cat_pipeline', cat_pipeline, cat_columns),
        ('num_pipeline', num_pipeline, num_columns)
        
    ],
    remainder = 'passthrough'
)

In [116]:
preprocessor

ColumnTransformer(remainder='passthrough',
                  transformers=[('cat_pipeline',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('ordinalencoder',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=-1))]),
                                 Index(['USERNAME', 'Hashtags'], dtype='object')),
                                ('num_pipeline',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 Index(['Followers'], dtype='object'))])

In [117]:
final_pipeline = Pipeline(
    steps = [
        ('preprocessor', preprocessor),
    ]
)

In [118]:
final_pipeline

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat_pipeline',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('ordinalencoder',
                                                                   OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                                  unknown_value=-1))]),
                                                  Index(['USERNAME', 'Hashtags'], dtype='object')),
                                                 ('num_pipeline',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['Followers'], dtype='object'))]))])

**Train & Test Split**

In [119]:
from sklearn.model_selection import train_test_split

In [120]:
X_train, X_test, y_train, y_test, = train_test_split(X, y, test_size = .20, random_state = 42)

In [121]:
final_pipeline.fit_transform(X_train)

array([[ 1.10000000e+01,  2.40000000e+01,  2.25514187e+00],
       [ 1.70000000e+01,  4.30000000e+01,  1.11499810e-01],
       [ 1.90000000e+01,  1.70000000e+01, -7.24426985e-01],
       [ 3.20000000e+01,  2.20000000e+01, -7.16938279e-01],
       [ 3.00000000e+01,  4.20000000e+01, -3.35938666e-02],
       [ 4.10000000e+01,  4.50000000e+01, -6.35486902e-02],
       [ 5.00000000e+01,  6.50000000e+01, -7.30979603e-01],
       [ 2.40000000e+01,  6.80000000e+01, -5.51250661e-01],
       [ 2.20000000e+01,  7.30000000e+01, -5.51250661e-01],
       [ 4.20000000e+01,  5.90000000e+01, -7.85261019e-02],
       [ 2.60000000e+01,  1.80000000e+01,  1.11685858e+00],
       [ 0.00000000e+00,  6.90000000e+01,  1.96589061e+00],
       [ 5.30000000e+01,  7.40000000e+01,  1.32560625e+00],
       [ 6.00000000e+01,  4.00000000e+00, -7.11321750e-01],
       [ 1.30000000e+01,  2.10000000e+01, -8.04930573e-01],
       [ 1.20000000e+01,  4.00000000e+01,  1.79834251e-01],
       [ 7.00000000e+01,  7.50000000e+01

In [122]:
final_pipeline.transform(X_test)

array([[-1.00000000e+00, -1.00000000e+00, -8.87306338e-01],
       [-1.00000000e+00, -1.00000000e+00, -8.91050691e-01],
       [-1.00000000e+00, -1.00000000e+00,  1.50815516e-01],
       [-1.00000000e+00, -1.00000000e+00, -8.58287603e-01],
       [-1.00000000e+00, -1.00000000e+00, -8.62031956e-01],
       [ 5.20000000e+01, -1.00000000e+00,  5.25250811e-01],
       [-1.00000000e+00, -1.00000000e+00,  1.97748640e-03],
       [-1.00000000e+00, -1.00000000e+00, -8.41438015e-01],
       [-1.00000000e+00, -1.00000000e+00, -8.33013221e-01],
       [ 5.20000000e+01, -1.00000000e+00,  5.25250811e-01],
       [-1.00000000e+00, -1.00000000e+00, -9.02283750e-01],
       [-1.00000000e+00, -1.00000000e+00, -1.97409308e-01],
       [-1.00000000e+00, -1.00000000e+00,  1.24791093e+00],
       [-1.00000000e+00, -1.00000000e+00, -4.01476544e-01],
       [-1.00000000e+00, -1.00000000e+00, -1.64646220e-01],
       [-1.00000000e+00, -1.00000000e+00, -6.87919544e-01],
       [-1.00000000e+00, -1.00000000e+00

In [123]:
X_train = pd.DataFrame(final_pipeline.fit_transform(X_train), columns = final_pipeline.get_feature_names_out())

In [124]:
X_train.head()

cat_pipeline__USERNAME  cat_pipeline__Hashtags  num_pipeline__Followers
0                    11.0                    24.0                 2.255142
1                    17.0                    43.0                 0.111500
2                    19.0                    17.0                -0.724427
3                    32.0                    22.0                -0.716938
4                    30.0                    42.0                -0.033594

In [125]:
X_test = pd.DataFrame(final_pipeline.transform(X_test), columns = final_pipeline.get_feature_names_out())

In [126]:
X_test.head()

cat_pipeline__USERNAME  cat_pipeline__Hashtags  num_pipeline__Followers
0                    -1.0                    -1.0                -0.887306
1                    -1.0                    -1.0                -0.891051
2                    -1.0                    -1.0                 0.150816
3                    -1.0                    -1.0                -0.858288
4                    -1.0                    -1.0                -0.862032

In [127]:
y_train

55    24
88     2
26     2
42     2
69     2
      ..
60     2
71     2
14     3
92     2
51     4
Name: Time since posted (hours), Length: 80, dtype: int64

**Model Training**

In [128]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [129]:
lin_reg = LinearRegression()

In [130]:
lin_reg.fit(X_train, y_train)

LinearRegression()

In [131]:
np.round(lin_reg.predict(X_test))

array([3., 3., 4., 3., 3., 4., 3., 3., 3., 4., 3., 3., 4., 3., 3., 3., 3.,
       3., 3., 3.])

In [132]:
lin_reg.coef_

array([-0.00656268,  0.00452546,  0.85065017])

In [133]:
lin_reg.intercept_

3.420928025514872

In [134]:
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mse)
    r2_square = r2_score(true, predicted)
    return mae, mse, rmse, r2_square

In [135]:
models = {
    "LinearRegression" : LinearRegression(),
    "Lasso" : Lasso(),
    "Ridge" : Ridge(),
    "ElasticNet" : ElasticNet()
}

model_list = []
mae_list = []
mse_list = []
rsme_list = []
r2_list = []

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train)
   

    # Make Prediction
    y_pred = model.predict(X_test)
    
    mae, mse, r2_square, rsme = evaluate_model(y_test, y_pred)
    

    print(list(models.keys())[i])

    model_list.append(list(models.keys())[i])

    print(f"Model Training Performance")
    print(f"Mean Absolute Error:{mae}")
    print(f"Mean Squared Error :{mse}")
    print(f"Root Mean Squared Error:{rsme}")
    print(f"R2_Score:{r2_square}")

    mae_list.append(mae)    
    mse_list.append(mse)
    rsme_list.append(rsme)
    r2_list.append(r2_square)
    

    print(f"MAE List:{mae_list}")
    print(f"MSE List:{mse_list}")
    print(f"RSME List:{rsme_list}")
    print(f"R2 List:{r2_list}")
    print('*'*100)
    print('\n')

LinearRegression
Model Training Performance
Mean Absolute Error:2.2293799010061983
Mean Squared Error :11.864303814517212
Root Mean Squared Error:-0.018613763856382137
R2_Score:3.4444598726821036
MAE List:[2.2293799010061983]
MSE List:[11.864303814517212]
RSME List:[-0.018613763856382137]
R2 List:[3.4444598726821036]
****************************************************************************************************


Lasso
Model Training Performance
Mean Absolute Error:2.348599312918906
Mean Squared Error :12.343137338696755
Root Mean Squared Error:-0.05972417589154344
R2_Score:3.5132801395130384
MAE List:[2.2293799010061983, 2.348599312918906]
MSE List:[11.864303814517212, 12.343137338696755]
RSME List:[-0.018613763856382137, -0.05972417589154344]
R2 List:[3.4444598726821036, 3.5132801395130384]
****************************************************************************************************


Ridge
Model Training Performance
Mean Absolute Error:2.229913907758115
Mean Squared Erro